apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: api
  project: default
  source:
    path: redis
    repoURL: https://bitbucket.org/cloudee/kube-install-argocd-demo.git
    targetRevision: HEAD
    helm:
      parameters:
      - name: image.repository
        value: {{ .Values.registry }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true 
