
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    haha: "lol"
spec:
  tls:
    - hosts:
      - {{ .Values.web.ingress }}
      secretName: ssl-web
  rules:
  - host: {{ .Values.web.ingress }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web
            port: 
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    category: application
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: web

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
    category: application
  name: web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
        svc: web
        category: application
    spec:
      containers:
      - image: {{ .Values.image.repository }}{{ .Values.web.image }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        -  name: API_URL
           value: "http://api.api"
        name: nodejs
        resources:
          requests:
            memory: 32Mi
            cpu: 10m
          limits:
            memory: 128Mi
            cpu: 2000m
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 5
      terminationGracePeriodSeconds: 5
