---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: {{ .Values.api.ingress }}
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: api
            port: 
              number: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-conf
  labels:
    category: application
data:
  REDIS_HOST: {{ .Values.api.redisHost }}
  

---
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  labels:
    category: application
data:
  SESSION_SECRET: {{ .Values.api.sessionSecret | b64enc | quote }}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
    category: application
  name: api
spec:
  ports:
  - port: 80
    targetPort: 3001
  selector:
    app: api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
    category: application
  name: api
spec:
  replicas: {{ .Values.api.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        category: application
    spec:
      containers:
      - image: {{ .Values.image.repository }}{{ .Values.api.image }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: nodejs
        resources:
          requests:
            memory: 512Mi
            cpu: 10m
          limits:
            memory: 1024Mi
            cpu: 1010m
        livenessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 30
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 2
          periodSeconds: 3
        envFrom:
        - configMapRef:
            name: api-conf
        - secretRef:
            name: api-secrets
      restartPolicy: Always
      terminationGracePeriodSeconds: 20 

