---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: report
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: {{ .Values.report.ingress }}
    http:
      paths:
      - path: /api/report
        pathType: Prefix
        backend:
          service:
            name: report
            port: 
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: report
    category: application
  name: report
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: report
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: report
    category: application
  name: report
spec:
  replicas: {{ .Values.report.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: report
  template:
    metadata:
      labels:
        app: report
        category: application
    spec:
      containers:
      - image: {{ .Values.image.repository }}{{ .Values.report.image }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: nginx
        volumeMounts:
        - name: conf
          mountPath: /etc/nginx/conf.d/
        resources:
          requests:
            memory: 16Mi
            cpu: 10m
          limits:
            memory: 128Mi
            cpu: 1010m
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 2
          periodSeconds: 3
      restartPolicy: Always
      terminationGracePeriodSeconds: 20 
      volumes:
        - name: conf
          configMap:
            name: report-nginx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: report-nginx
data:
  thelink.conf: |
    server {
        listen 80;

        location /api/report {
            default_type text/plain;
            expires -1;
            return 200 '{"message":"The feedback form is found at {{ .Values.feedback }}"}\n';
        }
        location / {
            default_type text/plain;
            expires -1;
            return 200 '{"message":"I am working"}\n';
        }
    }
